# Generated by Django 4.2.3 on 2023-08-18 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentista',
            name='nombre',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ci',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
