# Generated by Django 4.2.3 on 2023-08-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_remove_dentista_nombre_dentista_especialidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dentista',
            old_name='apellido',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='dentista',
            name='username',
        ),
        migrations.AlterField(
            model_name='dentista',
            name='especialidad',
            field=models.CharField(max_length=50),
        ),
    ]
