# Generated by Django 4.2.3 on 2023-08-30 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_alter_profesional_options_alter_profesional_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profesional',
        ),
    ]
